List<Map<String, dynamic>> ticketList = [
  {
    'from': {'code': 'NYC', 'name': 'New York'},
    'to': {'code': 'LDN', 'name': 'London'},
    'flying time': '8H 20M',
    'date': '1 May',
    'depature_Time': '08:00 AM',
    'number': '23',
  },
  {
    'from': {'code': 'DN', 'name': 'Den Mark'},
    'to': {'code': 'SDN', 'name': 'Sweden'},
    'flying time': '2H 10M',
    'date': '2 June',
    'depature_Time': '06:00 PM',
    'number': '05',
  },
  {
    'from': {'code': 'IND', 'name': 'India'},
    'to': {'code': 'NA', 'name': 'North America'},
    'flying time': '5H 03M',
    'date': '6 January',
    'depature_Time': '02:00 AM',
    'number': '10',
  },
  {
    'from': {'code': 'Uk', 'name': 'United Kingdom'},
    'to': {'code': 'IT', 'name': 'Italy'},
    'flying time': '1H 00M',
    'date': '6 february',
    'depature_Time': '05:00 AM',
    'number': '5',
  },
  {
    'from': {'code': 'IN', 'name': 'Indonesia'},
    'to': {'code': 'SA', 'name': 'South America'},
    'flying time': '1H 60M',
    'date': '8 December',
    'depature_Time': '04:00 PM',
    'number': '2',
  },
  {
    'from': {'code': 'UA', 'name': 'Ukanda'},
    'to': {'code': 'WK', 'name': 'Wakanda'},
    'flying time': '4H 3M',
    'date': '10 March',
    'depature_Time': '19:00 PM',
    'number': '7',
  },
];
